apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver 
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
      # change image to goserver if run pipeline using GitOps with ArgoCD
        image: registry.hub.docker.com/19061977/gitops_with_jenkins:{{tag}} 
        ports:
        - containerPort: 8081
