apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: registry.hub.docker.com/19061977/gitops_with_jenkins
  newTag: 6733e2167b52b40c4e1e2966fc380c3eceef9b02
